# Generated by Django 6.1.1 on 2026-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN')),
                ('editora', models.CharField(blank=True, default='', max_length=100)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de publicação')),
                ('exemplares', models.PositiveIntegerField(default=1, verbose_name='Exemplares')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
